BEGIN;

CREATE TYPE state AS ENUM ('new', 'old', 'deleted');

CREATE TABLE IF NOT EXISTS sources (
id SERIAL NOT NULL PRIMARY KEY,
name VARCHAR NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS entities (
id SERIAL NOT NULL PRIMARY KEY,
state state NOT NULL DEFAULT 'new',
action VARCHAR,
source_id INT REFERENCES sources(id) ON DELETE SET NULL,
is_processed BOOLEAN NOT NULL DEFAULT FALSE,
created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

COMMIT;